language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131

notifications:
  email: false

branches:  
  only:
    - master

before_install:  
  - chmod +x build.sh

script:  
  - ./build.sh