language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      mono: none
      dotnet: 2.0.0

notifications:
  email: false

branches:  
  only:
    - master

before_install:  
  - chmod +x build.sh

script:  
  - ./build.sh