environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  COVERALLS_TOKEN:
    secure: 9e+vrJ65VDmTcwWipInm3fmWWnG1cLYLsoQHnKkroGtLHTkUvTJ9w8KwD12W0u0w

install:
- sh: chmod +x build.sh

build_script:
- ps: .\build.ps1
- sh: ./build.sh

test: off
skip_tags: true
skip_branch_with_pr: true
image: 
- Visual Studio 2017
- Ubuntu